-- Script SQL pour ajouter des questions au workshop_maintenance
-- À exécuter dans Supabase SQL Editor

-- Insérer des questions pour le workshop Maintenance
INSERT INTO questions (
  title,
  question,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_answer,
  category,
  quiz_type,
  etape,
  points,
  active,
  order_index,
  workshop_id,
  feedback,
  explanation
) VALUES
(
  'Mission principale de la Maintenance',
  'Quelle est la mission principale du département Maintenance chez CIPREL ?',
  'Assurer la disponibilité et la fiabilité des équipements de production',
  'Gérer les achats de pièces détachées uniquement',
  'Former les nouveaux employés',
  'Superviser la production',
  ARRAY['A'],
  'DEFINITION',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  1,
  'workshop_maintenance',
  'La maintenance vise principalement à garantir la disponibilité des équipements.',
  'Le département Maintenance a pour mission essentielle d''assurer la disponibilité et la fiabilité des équipements pour garantir une production continue.'
),
(
  'Types de maintenance',
  'Quels sont les deux principaux types de maintenance pratiqués chez CIPREL ?',
  'Maintenance préventive et maintenance corrective',
  'Maintenance externe et maintenance interne',
  'Maintenance rapide et maintenance lente',
  'Maintenance manuelle et maintenance automatique',
  ARRAY['A'],
  'COMPETENCES',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  2,
  'workshop_maintenance',
  'La maintenance préventive (80%) et corrective sont les deux piliers.',
  'CIPREL pratique principalement la maintenance préventive (inspections, contrôles réguliers) représentant 80% des activités, et la maintenance corrective (diagnostic, remise en état).'
),
(
  'Maintenance préventive',
  'Quel pourcentage représente la maintenance préventive dans les activités de maintenance chez CIPREL ?',
  '80%',
  '50%',
  '20%',
  '100%',
  ARRAY['A'],
  'COMPETENCES',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  3,
  'workshop_maintenance',
  'La maintenance préventive représente 80% des activités.',
  'La maintenance préventive, incluant les inspections et contrôles réguliers, représente environ 80% des activités du département.'
),
(
  'Rôle du Technicien de Maintenance',
  'Quel est le rôle principal du Technicien de Maintenance ?',
  'Réaliser les interventions techniques préventives et correctives',
  'Uniquement superviser les sous-traitants',
  'Gérer le budget du département',
  'Former les opérateurs de production',
  ARRAY['A'],
  'RESPONSABILITE',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  4,
  'workshop_maintenance',
  'Le technicien réalise les interventions techniques.',
  'Le Technicien de Maintenance est responsable de la réalisation des interventions techniques, qu''elles soient préventives ou correctives.'
),
(
  'Compétences techniques requises',
  'Quelles compétences techniques sont essentielles pour un agent de maintenance ?',
  'Électricité, mécanique, hydraulique et pneumatique',
  'Comptabilité et gestion financière',
  'Marketing et communication',
  'Ressources humaines',
  ARRAY['A'],
  'COMPETENCES',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  5,
  'workshop_maintenance',
  'Les compétences techniques multidisciplinaires sont essentielles.',
  'Un agent de maintenance doit maîtriser plusieurs domaines techniques : électricité, mécanique, hydraulique et pneumatique pour intervenir efficacement.'
),
(
  'GMAO',
  'Que signifie GMAO dans le contexte de la maintenance ?',
  'Gestion de Maintenance Assistée par Ordinateur',
  'Gestion des Matériaux et Achats Opérationnels',
  'Guide des Méthodes et Applications Opérationnelles',
  'Gestion du Matériel et des Approvisionnements',
  ARRAY['A'],
  'DEFINITION',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  6,
  'workshop_maintenance',
  'GMAO = Gestion de Maintenance Assistée par Ordinateur.',
  'La GMAO (Gestion de Maintenance Assistée par Ordinateur) est un outil informatique essentiel pour planifier et suivre les activités de maintenance.'
),
(
  'Savoir-être en maintenance',
  'Quel savoir-être est particulièrement important pour un professionnel de la maintenance ?',
  'Rigueur, réactivité et travail en équipe',
  'Créativité artistique',
  'Compétences commerciales',
  'Capacité de négociation',
  ARRAY['A'],
  'COMPETENCES',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  7,
  'workshop_maintenance',
  'Rigueur et réactivité sont essentielles en maintenance.',
  'La rigueur dans l''exécution, la réactivité face aux pannes et la capacité à travailler en équipe sont des qualités indispensables.'
),
(
  'Arrêts programmés',
  'Pourquoi les arrêts programmés sont-ils importants en maintenance ?',
  'Pour effectuer des interventions préventives sans impacter la production',
  'Pour permettre aux employés de prendre des vacances',
  'Pour réduire la consommation d''énergie',
  'Pour former de nouveaux employés',
  ARRAY['A'],
  'RESPONSABILITE',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  8,
  'workshop_maintenance',
  'Les arrêts programmés permettent la maintenance préventive.',
  'Les arrêts programmés permettent de réaliser des interventions de maintenance préventive de manière planifiée, minimisant ainsi l''impact sur la production.'
),
(
  'Documentation technique',
  'Pourquoi la documentation technique est-elle importante en maintenance ?',
  'Pour assurer la traçabilité et le partage des connaissances',
  'Pour décorer les bureaux',
  'Uniquement pour les audits externes',
  'Elle n''est pas importante',
  ARRAY['A'],
  'COMPETENCES',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  9,
  'workshop_maintenance',
  'La documentation assure traçabilité et partage de connaissances.',
  'Une bonne documentation technique permet d''assurer la traçabilité des interventions, de partager les connaissances et de faciliter les futures interventions.'
),
(
  'Sécurité en maintenance',
  'Quel est le premier réflexe avant toute intervention de maintenance ?',
  'Consigner et sécuriser l''équipement',
  'Commencer immédiatement le travail',
  'Appeler un collègue',
  'Vérifier ses emails',
  ARRAY['A'],
  'RESPONSABILITE',
  'WORKSHOP',
  'WORKSHOP',
  10,
  true,
  10,
  'workshop_maintenance',
  'La consignation et la sécurisation sont prioritaires.',
  'Avant toute intervention, il est impératif de consigner (mettre hors énergie) et de sécuriser l''équipement pour éviter tout accident.'
);

-- Vérifier les questions insérées
SELECT id, title, workshop_id, active FROM questions WHERE workshop_id = 'workshop_maintenance' ORDER BY order_index;
