-- ============================================================================
-- SQL IMPORT SCRIPT FOR WORKSHOP QUESTIONS FROM questions.json
-- ============================================================================
-- This script imports questions from questions.json into the questions table
-- Each quiz in the JSON becomes a set of questions with quiz_type = quiz title
--
-- USAGE:
-- 1. Review the questions.json file structure
-- 2. Run this script in your Supabase SQL Editor
-- 3. Verify import with: SELECT quiz_type, COUNT(*) FROM questions GROUP BY quiz_type;
--
-- NOTES:
-- - Questions will have etape based on their quiz_type
-- - UUIDs are auto-generated by the database
-- - Options are mapped from array format to individual columns (option_a, option_b, etc.)
-- - Correct answers are converted from single letter strings to uppercase array format
-- ============================================================================

-- First, let's create a temporary function to help with the import
-- This function will be removed at the end of this script

CREATE OR REPLACE FUNCTION import_quiz_question(
    p_title TEXT,
    p_question TEXT,
    p_options TEXT[],
    p_correct_answer TEXT,
    p_quiz_type TEXT,
    p_order_index INT
)
RETURNS UUID AS $$
DECLARE
    v_id UUID;
    v_correct_answer_array TEXT[];
    v_option_a TEXT;
    v_option_b TEXT;
    v_option_c TEXT;
    v_option_d TEXT;
BEGIN
    -- Extract options (remove the letter prefix like "a)", "b)", etc.)
    v_option_a := NULLIF(TRIM(REGEXP_REPLACE(p_options[1], '^[a-dA-D]\\)\\s*', '')), '');
    v_option_b := NULLIF(TRIM(REGEXP_REPLACE(p_options[2], '^[a-dA-D]\\)\\s*', '')), '');
    v_option_c := NULLIF(TRIM(REGEXP_REPLACE(p_options[3], '^[a-dA-D]\\)\\s*', '')), '');
    v_option_d := NULLIF(TRIM(REGEXP_REPLACE(p_options[4], '^[a-dA-D]\\)\\s*', '')), '');
    
    -- Convert correct answer to uppercase array format
    -- Handle multiple correct answers separated by comma or "A, C, D" format
    IF p_correct_answer ~ ',' THEN
        -- Multiple answers: convert "A, C, D" or "a, c" to ['A', 'C', 'D']
        v_correct_answer_array := STRING_TO_ARRAY(UPPER(REGEXP_REPLACE(p_correct_answer, '\\s', '', 'g')), ',');
    ELSE
        -- Single answer: convert "b" or "B" to ['B']
        v_correct_answer_array := ARRAY[UPPER(TRIM(p_correct_answer))];
    END IF;
    
    -- Insert the question and return the generated UUID
    INSERT INTO public.questions (
        title,
        question,
        option_a,
        option_b,
        option_c,
        option_d,
        correct_answer,
        category,
        quiz_type,
        etape,
        points,
        active,
        order_index,
        feedback,
        explanation,
        created_at,
        updated_at
    ) VALUES (
        p_title,
        p_question,
        v_option_a,
        v_option_b,
        v_option_c,
        v_option_d,
        v_correct_answer_array,
        'OPINION',  -- Default category for workshop questions
        p_quiz_type,
        'WORKSHOP',  -- All questions from JSON are workshop questions
        1,  -- Default points
        true,  -- Active by default
        p_order_index,
        NULL,  -- No feedback in JSON
        NULL,  -- No explanation in JSON
        NOW(),
        NOW()
    )
    RETURNING id INTO v_id;
    
    RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- IMPORT QUESTIONS FROM EACH QUIZ
-- ============================================================================
-- Note: You'll need to manually add the INSERT statements based on questions.json
-- Or use the sync-questions API endpoint which does this programmatically
--
-- The format for each question import would be:
-- SELECT import_quiz_question(
--     'Question Title',
--     'Question Text',
--     ARRAY['a) Option A', 'b) Option B', 'c) Option C', 'd) Option D'],
--     'b',  -- or 'A, C, D' for multiple
--     'Quiz de la DAF',
--     1  -- order index
-- );
--
-- ============================================================================

-- Example for the first few questions from "Quiz de la DAF":

SELECT import_quiz_question(
    'Rôle de l''équipe Comptabilité',
    'Quel est le rôle principal de l''équipe Comptabilité (Adjoint/Comptable) au sein du pôle Finance ?',
    ARRAY[
        'a) Gérer les relations bancaires.',
        'b) Traiter et consolider les opérations comptables et financières, et traiter les données fiscales.',
        'c) Élaborer le budget prévisionnel de l''entreprise.',
        'd) Optimiser les processus d''achat.'
    ],
    'b',
    'Quiz de la DAF',
    1
);

SELECT import_quiz_question(
    'Mission du Contrôleur de Gestion',
    'Selon la présentation, quelle est la mission centrale du Contrôleur de Gestion ?',
    ARRAY[
        'a) Assurer le reporting hebdomadaire des soldes bancaires.',
        'b) Élaborer le budget (plan financier) et effectuer le suivi rigoureux de sa mise en œuvre.',
        'c) Piloter le système d''informations financières (SIF).',
        'd) Gérer les contentieux douaniers.'
    ],
    'b',
    'Quiz de la DAF',
    2
);

-- ============================================================================
-- IMPORTANT NOTE:
-- ============================================================================
-- Rather than manually adding all questions here, it's recommended to use
-- the existing sync-questions API endpoint which programmatically imports
-- all questions from questions.json:
--
-- POST /api/admin/sync-questions
--
-- This endpoint:
-- 1. Reads questions.json
-- 2. Deletes existing questions for each quiz_type
-- 3. Inserts all questions with proper mapping
-- 4. Handles the conversion of options and correct answers automatically
--
-- This is more maintainable and less error-prone than manual SQL imports.
-- ============================================================================

-- Clean up: Drop the temporary import function
DROP FUNCTION IF EXISTS import_quiz_question(TEXT, TEXT, TEXT[], TEXT, TEXT, INT);

-- Verification query - Run this after import to verify
SELECT 
    quiz_type, 
    COUNT(*) as question_count,
    COUNT(*) FILTER (WHERE active = true) as active_count
FROM public.questions 
WHERE etape = 'WORKSHOP'
GROUP BY quiz_type
ORDER BY quiz_type;
