-- ============================================================================
-- COMPLETE SQL IMPORT - 104 QUESTIONS CIPREL (FIXED)
-- Tous les quiz_type sont maintenant WORKSHOP pour WORKSHOP questions
-- ============================================================================
BEGIN;
DELETE FROM public.questions;

-- INTRODUCTION QUESTIONS (7)
INSERT INTO public.questions (id, title, question, option_a, option_b, option_c, option_d, correct_answer, category, quiz_type, etape, points, active, order_index, feedback, explanation, created_at, updated_at) VALUES
('0ab98d19-a41e-4cb5-ae5c-d798c771d00b'::uuid, 'Définition de la démarche compétence', 'La démarche compétence c''est :', 'Un moyen de retenir les potentiels et les talents', 'Un levier de performance', 'Un levier de certification qualité', NULL, ARRAY['A','B'], 'DEFINITION', 'INTRODUCTION', 'INTRODUCTION', 2, true, 1, 'Excellente réponse !', 'Vise à optimiser ressources humaines', NOW(), NOW()),
('439dbbad-fe02-418b-8165-b731081bcb0a'::uuid, 'Responsabilité de la démarche compétence', 'La démarche compétence est la responsabilité de :', 'Tous', 'La direction générale', 'Le groupe ERANOVE', NULL, ARRAY['A'], 'RESPONSABILITE', 'INTRODUCTION', 'INTRODUCTION', 1, true, 2, 'Parfait !', 'Nécessite engagement de tous', NOW(), NOW()),
('4dcbb526-8033-4a44-ae2c-c48f9c7df76a'::uuid, 'Objectifs de la démarche compétence', 'La démarche compétence vise principalement à :', 'Réduire les coûts de formation', 'Améliorer la performance et l''employabilité', 'Standardiser les pratiques', NULL, ARRAY['B'], 'DEFINITION', 'INTRODUCTION', 'INTRODUCTION', 1, true, 6, 'Correct !', 'Optimiser performance organisationnelle', NOW(), NOW()),
('752aa449-c232-484c-81fb-35b0d347ab70'::uuid, 'Compétences requises pour manager', 'Pour manager, il faut avoir des compétences :', 'Techniques uniquement', 'Managériales uniquement', 'Techniques et managériales', NULL, ARRAY['C'], 'COMPETENCES', 'INTRODUCTION', 'INTRODUCTION', 1, true, 3, 'Correct !', 'Double compétence requise', NOW(), NOW()),
('819abea0-b021-437a-9620-f228813a2f4b'::uuid, 'Évaluation des compétences', 'L''évaluation des compétences permet de :', 'Sanctionner les lacunes', 'Identifier les écarts et planifier le développement', 'Classer les collaborateurs', NULL, ARRAY['B'], 'ETAPES', 'INTRODUCTION', 'INTRODUCTION', 1, true, 7, 'Excellent !', 'Outil de développement pas sanction', NOW(), NOW()),
('91b85227-4da3-4f18-a026-8b7472b0061b'::uuid, 'Types de compétences', 'Les compétences se déclinent en :', 'Savoir uniquement', 'Savoir et savoir-faire', 'Savoir, savoir-faire et savoir-être', NULL, ARRAY['C'], 'COMPETENCES', 'INTRODUCTION', 'INTRODUCTION', 1, true, 5, 'Parfait !', 'Trois dimensions essentielles', NOW(), NOW()),
('c3772dd7-be2e-4ea0-9a8d-ec13fe43182d'::uuid, 'Première étape de la démarche', 'La première étape de la démarche compétence consiste à :', 'Former les collaborateurs', 'Identifier les compétences requises', 'Évaluer les performances', NULL, ARRAY['B'], 'ETAPES', 'INTRODUCTION', 'INTRODUCTION', 1, true, 4, 'Exact !', 'Identification est le socle', NOW(), NOW());

-- SONDAGE QUESTIONS (6)
INSERT INTO public.questions (id, title, question, option_a, option_b, option_c, option_d, correct_answer, category, quiz_type, etape, points, active, order_index, feedback, explanation, created_at, updated_at) VALUES
('0802f174-d34f-4823-8b28-6b372a184b6e'::uuid, 'Inquiétudes', 'Avez-vous des inquiétudes concernant cette démarche ?', 'Surcharge de travail', 'Évaluation trop stricte', 'Manque de moyens', 'Aucune inquiétude', ARRAY['A','B','C','D'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 5, 'Nous prenons en compte préoccupations', NULL, NOW(), NOW()),
('1b702673-cb63-484e-8aed-196e080598c5'::uuid, 'Bénéfices perçus', 'Selon vous quels sont principaux bénéfices pour CIPREL ?', 'Optimisation des ressources', 'Aide à évolution professionnelle', 'Meilleure adéquation besoins/compétences', 'Meilleure gestion des talents', ARRAY['A','B','C','D'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 3, 'Merci vision partagée', NULL, NOW(), NOW()),
('27e41cbe-1d34-4bac-8c9e-ee4779346a54'::uuid, 'Sources d''information souhaitées', 'Par quels moyens souhaiteriez-vous être informé ?', 'Réunions d''information', 'Communications internes', 'Formation spécifique', 'Documentation en ligne', ARRAY['A','B','C','D'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 6, 'Nous adapterons communication', NULL, NOW(), NOW()),
('6201c31b-1051-4a86-93a4-fc1630398fd8'::uuid, 'Connaissance de la démarche compétence', 'Savez-vous ce que c''est la démarche compétence ?', 'Oui', 'Non', 'Vague idée', NULL, ARRAY['A','B','C'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 1, 'Merci réponse sincère', NULL, NOW(), NOW()),
('c2e93cde-2829-4a4d-8794-0af4e5510658'::uuid, 'Attentes personnelles', 'Quelles sont vos attentes vis-à-vis démarche ?', 'Développement personnel', 'Évolution carrière', 'Amélioration conditions travail', 'Reconnaissance compétences', ARRAY['A','B','C','D'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 4, 'Attentes guideront mise oeuvre', NULL, NOW(), NOW()),
('c3371e66-d3bf-463f-8b6f-6152b601f7c3'::uuid, 'Définition personnelle', 'Comment définiriez-vous la démarche compétence ?', 'Processus RH', 'Outil développement', 'Stratégie d''entreprise', 'Autre', ARRAY['A','B','C','D'], 'OPINION', 'SONDAGE', 'SONDAGE', 0, true, 2, 'Vision précieuse', NULL, NOW(), NOW());

-- WORKSHOP QUESTIONS - ALL 91 Questions (DAF, RH, Stocks, Projets, SITD, Achats, Services, QSE, Production, Intro)
INSERT INTO public.questions (title, question, option_a, option_b, option_c, option_d, correct_answer, category, quiz_type, etape, points, active, order_index, created_at, updated_at) VALUES
('Rôle Comptabilité DAF', 'Quel est le rôle principal équipe Comptabilité ?', 'Gérer relations bancaires', 'Traiter et consolider opérations comptables', 'Élaborer budget prévisionnel', 'Optimiser processus achat', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 1, NOW(), NOW()),
('Mission Contrôleur Gestion DAF', 'Quelle est mission centrale Contrôleur Gestion ?', 'Assurer reporting hebdomadaire', 'Élaborer budget et suivi mise oeuvre', 'Piloter système informations financières', 'Gérer contentieux douaniers', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 2, NOW(), NOW()),
('Trésorerie Responsabilités DAF', 'Quelle est responsabilité principale Trésorerie ?', 'Réaliser inventaires stock', 'Gérer flux trésorerie et relations bancaires', 'Coordonner activités RSE', 'Assurer sécurité physique', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 3, NOW(), NOW()),
('Pilotage SIF DAF', 'Qui est chargé Piloter SIF ?', 'Contrôleur Gestion', 'Trésorier', 'Adjoint comptabilité', 'Leadership', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 4, NOW(), NOW()),
('Valeur Comptabilité DAF', 'Quelle valeur Comptabilité assure ?', 'Convivialité', 'Innovation', 'Respect', 'Force Collectif', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 5, NOW(), NOW()),
('Mission Fiabilité Info DAF', 'Mission assure fiabilité informations ?', 'Améliorer fiabilité infos financières', 'Traiter décaissements', 'Gérer placements', 'Coordonner logistique', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 6, NOW(), NOW()),
('Équité Trésorerie DAF', 'Comment Trésorerie démontre Équité ?', 'Ne travaillant qu''une banque', 'Engagement jamais dettes', 'Reporting régulier et transparent', 'Élaborant contrats clients', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 7, NOW(), NOW()),
('Coordination Finance DAF', 'Quel rôle coordonne opérations comptables ?', 'Comptable', 'Contrôleur Gestion', 'Responsable Finance Comptabilité', 'Coordinateur Logistique', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 8, NOW(), NOW()),
('Force Collectif Finance DAF', 'Force Collectif Finance repose sur ?', 'Indépendance totale', 'Interdépendance des fonctions', 'Fusion rôles', 'Délégation externe', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 9, NOW(), NOW()),
('Objectif Final Finance DAF', 'Objectif final Pôle Finance ?', 'Enregistrer transactions', 'Réduire effectifs', 'Socle décisions futures et Maîtrise Risques', 'Relations actionnaires', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 10, NOW(), NOW()),
('Mission RH', 'Quelle est mission fondamentale RH ?', 'Gérer dossiers administratifs', 'Transformer talents en moteur performance', 'Surveiller installations techniques', 'Contrôler qualité production', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 11, NOW(), NOW()),
('Développement RH Objectif', 'Objectif principal Développement RH ?', 'Rédiger contrats travail', 'Préparer avenir développant compétences', 'Gérer paies absences', 'Assurer conformité réglementaire', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 12, NOW(), NOW()),
('Administration RH Rôle', 'Administration RH a pour rôle ?', 'Produire énergie électrique', 'Structurer sécuriser garantir conformité RH', 'Définir objectifs production', 'Gérer achats combustibles', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 13, NOW(), NOW()),
('Développement RH Activité', 'Activité appartient Développement RH ?', 'Élaboration paie', 'Constitution dossiers personnel', 'Analyse besoins recrutement et sourcing', 'Gestion visites médicales', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 14, NOW(), NOW()),
('Savoir-être RH', 'Savoir-être indispensable RH ?', 'Distance et froideur', 'Équité écoute et discrétion', 'Rigidité totale', 'Absence contact humain', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 15, NOW(), NOW()),
('Mission Juridique', 'Mission principale pôle Juridique ?', 'Piloter turbines', 'Produire eau déminéralisée', 'Sécuriser opérations et garantir légalité', 'Superviser formations', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 16, NOW(), NOW()),
('Rôle Juridique Clé', 'Rôle clé Juridique ?', 'Évaluer collaborateurs', 'Rédiger contrats et protéger contre risques', 'Organiser plannings production', 'Superviser achats techniques', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 17, NOW(), NOW()),
('Valeur FEERIC RH Juridique', 'Valeur FEERIC indispensable RH Juridique ?', 'Individualisme', 'Précipitation', 'Équité', 'Agressivité', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 18, NOW(), NOW()),
('Lien Développement Administration', 'Lien Développement et Administration RH ?', 'Travaillent côtés', 'Opposition permanente', 'Complémentarité transforme besoins en solutions', 'Gèrent uniquement formations', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 19, NOW(), NOW()),
('Éthique Juridique', 'Rôle Juridique matière éthique ?', 'Assurer production électrique nuit', 'Concentrer sur procès', 'Garantir transparence gouvernance et prévenir corruption', 'Gérer congés personnel', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 20, NOW(), NOW()),
('Rôle Gestion Stocks', 'Rôle stratégique principal Gestion Stocks ?', 'Négocier prix fournisseurs', 'Assurer sécurité physique site', 'Premier rempart défaillance garantir disponibilité pièces vitales', 'Calculer amortissements', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 21, NOW(), NOW()),
('Immobilisation Financière', 'Mission pôle immobilisation financière ?', 'Maximiser volume stock', 'Éliminer tous stocks', 'Optimiser capital immobilisé minimisant surstockage tout maximisant sécurité', 'Négocier taux intérêt', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 22, NOW(), NOW()),
('Fiabilité Données Stock', 'Fonction garantit fiabilité données stock ?', 'Contrôle qualitatif réception', 'Distribution interne pièces', 'Gestion mouvements physiques', 'Réalisation inventaires', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 23, NOW(), NOW()),
('Vision Globale Stocks', 'Titre fonction assure vision globale pôle ?', 'Gestionnaire Stock', 'Responsable Achat Logistique', 'Coordinateur Gestion Stock', 'Acheteur', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 24, NOW(), NOW()),
('Rapports Transparence', 'Rapport assurer transparence ?', 'Rapports évaluation fournisseurs', 'États financiers annuels', 'Rapports liés gestion activité', 'Études marché', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 25, NOW(), NOW()),
('Valeur Équité Stocks', 'Valeur liée mission Équité stocks ?', 'Innovation', 'Convivialité', 'Force Collectif', 'Équité', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 26, NOW(), NOW()),
('Paramètres Gestion', 'Signifie ''Suivre paramètres gestion stocks'' ?', 'Mémoriser emplacement exact', 'Définir niveaux analyser indicateurs', 'Vérifier licences logicielles', 'Organiser réunions Convivialité', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 27, NOW(), NOW()),
('Mouvements Physiques', 'Pourquoi gérer mouvements physiques avec Respect ?', 'Camions aient assez espace', 'Minimiser usure équipements', 'Garantir traçabilité intégrité conformité données', 'Prouver Force Collectif', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 28, NOW(), NOW()),
('Stock de Sécurité', 'Rôle ''Stock Sécurité'' ?', 'Gérer fournitures bureau', 'Contrôler niveau selon demande marché', 'Assurer gestion pièces uniques critiques centrale', 'Protéger données informatiques', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 29, NOW(), NOW()),
('Innovation Stocks', 'Pôle Gestion Stocks utilise Innovation comment ?', 'Inventant nouvelles pièces', 'Utilisant uniquement méthodes manuelles', 'Développant partenariats bancaires', 'Intégrant systèmes WMS vision précise temps réel', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 30, NOW(), NOW()),
('Rôle Responsable Projets', 'Rôle stratégique Responsable Projets ?', 'Superviser travail administratif', 'Garantir alignement avec orientations stratégiques', 'Assurer maintenance installations', 'Réaliser suivi quotidien prestataires', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 31, NOW(), NOW()),
('Directeur Développement', 'Directeur Développement assure performance ?', 'Définissant standards méthodologiques', 'Coordonnant uniquement recrutements', 'Pilotant feuille route développement', 'Supervisant rôles opérationnels', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 32, NOW(), NOW()),
('Superviseur Projets', 'Superviseur Projets contribue performance ?', 'Réalisant suivi technique opérationnel', 'Rédigeant contrats fournisseurs', 'Formant opérateurs production', 'Gérant archives administratives', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 33, NOW(), NOW()),
('Superviseur Risques', 'Mission Superviseur Projets inclut ?', 'Contrôle respect normes QHSE', 'Identification risques opérationnels', 'Coordination plannings paie', 'Supervision prestataires site', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 34, NOW(), NOW()),
('Assistante Projets', 'Rôle principal Assistante Projets ?', 'Réaliser audits QHSE', 'Actualiser documentation projet assurer circulation infos', 'Gérer interventions techniques', 'Élaborer stratégies investissement', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 35, NOW(), NOW()),
('Secrétaire Projets', 'Secrétaire Projets contribue conformité ?', 'Organisant réunions', 'Assurant archivage structuré traçabilité', 'Rédigeant procès-verbaux', 'Supervisant installations électriques', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 36, NOW(), NOW()),
('Intégrité Projets', 'Pôle Projets Intégrité traduit par ?', 'Strict respect délais production', 'Transparence contractualisation et reporting', 'Innovation permanente', 'Gestion exclusive communication', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 37, NOW(), NOW()),
('Standards CIPREL', 'Projet aligné standards CIPREL ?', 'Renforce continuité et fiabilité', 'Respecte normes QHSE', 'Livré avant date prévue', 'Intègre critères ESG', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 38, NOW(), NOW()),
('Collaboration Projets', 'Collaboration pôle Projets repose sur ?', 'Autonomie complète chaque rôle', 'Synchronisation rigoureuse entre stratégie et support', 'Délégation prestataires externes', 'Reporting annuel unique', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 39, NOW(), NOW()),
('Risques Énergétiques', 'Risques critiques incluent ?', 'Risques techniques', 'Risques opérationnels', 'Risques administratifs', 'Risques conformité réglementaire et environnementale', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 40, NOW(), NOW()),
('Objectif SIDT', 'SIDT joue rôle essentiel objectif principal ?', 'Garantir sécurité systèmes information', 'Gérer exclusivement contrats', 'Accompagner transformation digitale', 'Assurer disponibilité et fiabilité outils numériques', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 41, NOW(), NOW()),
('Pôles SIDT', 'Trois pôles clés SIDT ?', 'Responsable Informatique Veille', 'Responsable Maintenance Industrielle', 'Ingénieur Informatique', 'Technicien Informatique', ARRAY['A','C','D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 42, NOW(), NOW()),
('Cybersécurité Ingénieur', 'Rôle Ingénieur Informatique cybersécurité ?', 'Sensibilisation utilisateurs', 'Intégration mécanismes techniques protection', 'Rédaction chartes', 'Contrôle qualité support', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 43, NOW(), NOW()),
('Technicien Informatique', 'Technicien Informatique a pour rôle ?', 'D''assurer support proximité', 'Maintenir et installer équipements', 'Rédiger politiques', 'Garantir continuité opérationnelle', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 44, NOW(), NOW()),
('Piliers SIDT', 'Piliers structurent mission SIDT ?', 'Moderniser et sécuriser systèmes information', 'Améliorer transformation digitale', 'Optimiser lignes production', 'Anticiper évolutions technologiques', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 45, NOW(), NOW()),
('Cybersécurité Valeur', 'Valeur CIPREL plan cybersécurité ?', 'Innovation', 'Intégrité', 'Excellence', 'Convivialité', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 46, NOW(), NOW()),
('Collaboration SIDT', 'SIDT se distingue par ?', 'Forte complémentarité entre rôles', 'Travail isolé', 'Rôle stratégique faciliter travail', 'Contribution directe fiabilité', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 47, NOW(), NOW()),
('ESG SIDT', 'Matière ESG SIDT contribue ?', 'Renforcer cybersécurité', 'Réduire empreinte environnementale', 'Concevoir politique RH', 'Intégrer solutions technologiques responsables', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 48, NOW(), NOW()),
('Positionnement SIDT', 'SIDT se positionne comme ?', 'Simple support technique', 'Partenaire stratégique performance', 'Acteur clé sécurité technologique', 'Moteur transformation digitale durable', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 49, NOW(), NOW()),
('Rôle Achats Logistique', 'Double rôle principal Pôle Achats Logistique ?', 'Gérer RH et communication', 'Levier performance durable et garant continuité', 'Assurer marketing et ventes', 'Définir stratégie et politiques RSE', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 50, NOW(), NOW()),
('Éthique Achats', 'Mission fondamentale pôle Achats ?', 'Obtenir prix plus bas', 'Garant de éthique et loyauté pratiques', 'Rédiger tous contrats', 'Assurer sourcing local', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 51, NOW(), NOW()),
('Processus Achat', 'Processus d''Achat mission suit traitement besoins ?', 'Traitement contentieux douaniers', 'Gestion stocks sécurité', 'Assurer suivi achats', 'Négocier budgets', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 52, NOW(), NOW()),
('Mouvements Stocks', 'Responsable gestion mouvements physiques stocks ?', 'Acheteur', 'Responsable Achat Logistique', 'Coordinateur Logistique', 'Fonction développée séparément', ARRAY['D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 53, NOW(), NOW()),
('Conformité Importations', 'Logistique garantit conformité importations ?', 'S''occupant transport maritime', 'Déléguant fournisseurs', 'Assurant traitement dossiers et contentieux douaniers', 'Évaluant fournisseurs', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 54, NOW(), NOW()),
('Engagement Partenaires', 'Valeur illustre ''transformer engagement partenaires'' ?', 'Innovation', 'Respect', 'Engagement', 'Équité', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 55, NOW(), NOW()),
('Évaluation Fournisseurs', 'Évaluation fournisseurs assure ?', 'Convivialité', 'Force collectif', 'Équité', 'Logistique', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 56, NOW(), NOW()),
('Direction Pôle', 'Titre assure vision globale pôle ?', 'Acheteur', 'Responsable Achat Logistique', 'Coordinateur Achat', 'Coordinateur Logistique', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 57, NOW(), NOW()),
('Force Collectif Achats', 'Force Collectif s''applique-t-elle ?', 'Minimisant interactions', 'Favorisant collaboration et fluidité', 'Négociant individuellement', 'Optimisant uniquement coûts', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 58, NOW(), NOW()),
('Critères RSE Fournisseurs', 'Critère RSE intègre pôle Achats ?', 'Ancienneté fournisseur', 'Capacité fournir un seul type', 'Intégration critères ESG', 'Rapidité réponse', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 59, NOW(), NOW()),
('Mission Services Généraux', 'Mission principale Services Généraux ?', 'Produire l''énergie', 'Assurer environnement travail fonctionnel et sécurisé', 'Former nouveaux collaborateurs', 'Garantir qualité eau', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 60, NOW(), NOW()),
('Intervention Services Généraux', 'Services Généraux interviennent ?', 'Gérer installations et besoins matériels', 'Superviser turbines', 'Assurer conformité financière', 'Piloter production énergie', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 61, NOW(), NOW()),
('Savoir-faire Services Généraux', 'Savoir-faire essentiel ?', 'Réaliser analyses chimiques', 'Ajuster puissance électrique', 'Planifier et suivre maintenance installations', 'Diagnostiquer moteurs turbines', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 62, NOW(), NOW()),
('Savoir-être Services Généraux', 'Savoir-être indispensable ?', 'Individualisme', 'Disponibilité et sens du service', 'Agressivité', 'Distanciation totale', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 63, NOW(), NOW()),
('Interaction Services Généraux', 'Interaction typique ?', 'Dialogue salle commande', 'Coordination quotidienne avec tous départements', 'Intervention calibrage équipements', 'Relation autorités électriques', ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 64, NOW(), NOW()),
('Fierté Services Généraux', 'Fierté principale du métier ?', 'Gestion réseau électrique national', 'Optimisation production', 'Que tout fonctionne et soit disponible', 'Pilotage installations', ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 65, NOW(), NOW()),
('Savoir Services Généraux', 'Type savoir doivent-ils maîtriser ?', 'Normes hygiène et sécurité', 'Algorithmes d''ajustement tension', 'Procédures mise en service turbines', 'Fonctionnement chimique eau', ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 66, NOW(), NOW()),
('Rôle QSE RSE', 'Rôle principal Pôle QSE-RSE Sûreté ?', 'Superviser qualité produits', 'Garantir qualité sécurité sûreté et responsabilité sociale', 'Gérer stocks', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 67, NOW(), NOW()),
('Mission QSE RSE', 'Mission première service QSE-RSE ?', 'Faire respecter réglementation environnementale', 'Intégrer durabilité dans chaque processus', 'Établir statistiques sur incidents', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 68, NOW(), NOW()),
('Rôle Sûreté', 'Service Sûreté a pour rôle ?', 'Protéger installations et personnel contre risques', 'Gérer propreté site', 'Surveiller uniquement centrale', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 69, NOW(), NOW()),
('Slogan QSE', 'Slogan Pôle QSE-RSE résume ?', 'Démarche Compétence', 'Agir responsable opérer sécurité exceller qualité', 'Plan urgence interne', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 70, NOW(), NOW()),
('Contribution QSE', 'Métiers QSE-RSE contribuent ?', 'Performance économique uniquement', 'Performance durable et confiance', 'Optimisation budgets', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 71, NOW(), NOW()),
('Excellence QSE', 'Pour exceller dans ce métier ?', 'Connaître lois et procédures', 'Avoir goût pour risque', 'Être indifférent aux normes', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 72, NOW(), NOW()),
('Valeur FEERIC QSE', 'Valeur FEERIC illustrant culture QSE ?', 'Force collectif', 'Innovation', 'Respect', NULL, ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 73, NOW(), NOW()),
('Responsabilité Sûreté', 'Matière Sûreté chaque employé CIPREL ?', 'Acteur passif', 'Premier responsable sûreté', 'Exempté consignes', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 74, NOW(), NOW()),
('Partenaires QSE', 'Partenaires externes Pôle QSE ?', 'Autorités régulation et organismes certification', 'Fournisseurs énergie', 'Médias', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 75, NOW(), NOW()),
('Fierté QSE', 'Plus grande fierté équipes QSE ?', 'Ne pas avoir rapports rédiger', 'Garantir que chaque collaborateur rentre sain et sauf', 'Gérer logistique site', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 76, NOW(), NOW()),
('Production CIPREL', 'Production CIPREL c''est ?', 'Fonction administrative', 'Cœur opérationnel centrale électrique', 'Activité maintenance', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 77, NOW(), NOW()),
('Pôles Production', 'Pôle Production est composé ?', 'Conduite et Maintenance', 'Conduite et Chimie', 'Maintenance et QSE-RSE', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 78, NOW(), NOW()),
('Rôle Techniciens', 'Techniciens Conduite ont pour rôle ?', 'Réaliser audits sécurité', 'Veiller bon fonctionnement machines', 'Élaborer plans communication', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 79, NOW(), NOW()),
('Conducteurs Installation', 'Conducteurs d''installation ?', 'Animation ateliers RH', 'Pilotage et surveillance depuis salle commande', 'Maintenance systèmes électriques', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 80, NOW(), NOW()),
('Mission Chimistes', 'Chimistes ont pour mission ?', 'Produire et contrôler eau déminéralisée et vapeur', 'Surveiller stocks combustibles', 'Vérifier comptes production', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 81, NOW(), NOW()),
('Savoir-faire Production', 'Savoir-faire dans Production ?', 'Capacité diagnostiquer et piloter', 'Attitude positive en équipe', 'Connaissance consignes sécurité', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 82, NOW(), NOW()),
('Savoir-être Conduite', 'Savoir-être attendu opérateur ?', 'Autonomie créativité curiosité', 'Rigueur réactivité vigilance et esprit équipe', 'Ambition et goût risque', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 83, NOW(), NOW()),
('Partenaires Production', 'Partenaires internes Pôle Production ?', 'Autorités électriques', 'Maintenance QSE-RSE RH Projets Achats', 'Fournisseurs combustibles', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 84, NOW(), NOW()),
('Slogan Production', 'Slogan Pôle Production ?', 'Nos installations notre réussite', 'Nos compétences notre énergie', 'Produire mieux dépenser moins', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 85, NOW(), NOW()),
('Démarche Compétence Intro', 'Démarche compétence c''est ?', 'Retenir potentiels et talents', 'Levier de performance', 'Certification qualité', NULL, ARRAY['B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 86, NOW(), NOW()),
('Responsabilité Démarche Intro', 'Démarche compétence responsabilité ?', 'Tous', 'Direction générale', 'Groupe ERANOVE', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 87, NOW(), NOW()),
('Compétences Types Intro', 'Compétences sont essentiellement ?', 'Techniques', 'Comportementales', 'Fondamentales', NULL, ARRAY['A','B'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 88, NOW(), NOW()),
('Savoir-faire Définition Intro', 'Savoir-faire c''est ?', 'Capacité assurer tâches techniques', 'Capacités cognitives et relationnelles', 'Capacité bien faire choses', NULL, ARRAY['A'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 89, NOW(), NOW()),
('Savoir-être Définition Intro', 'Savoir-être c''est ?', 'Connaissances cumulées par expérience', 'Capacité agir dans son environnement', 'Capacités cognitives et relationnelles', NULL, ARRAY['C'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 90, NOW(), NOW()),
('Étapes Démarche Intro', 'Étapes démarche compétence ?', 'Identification compétences requises', 'Développer compétences', 'Challenger méritants', 'Cartographier et évaluer', ARRAY['A','B','D'], 'OPINION', 'WORKSHOP', 'WORKSHOP', 1, true, 91, NOW(), NOW());

COMMIT;

-- VERIFICATION
SELECT 'FINAL STATUS' as check_type, 'SUCCESS' as result
UNION ALL
SELECT 'Total questions', COUNT(*)::text FROM public.questions
UNION ALL
SELECT 'INTRODUCTION', COUNT(*)::text FROM public.questions WHERE quiz_type = 'INTRODUCTION'
UNION ALL
SELECT 'SONDAGE', COUNT(*)::text FROM public.questions WHERE quiz_type = 'SONDAGE'
UNION ALL
SELECT 'WORKSHOP', COUNT(*)::text FROM public.questions WHERE quiz_type = 'WORKSHOP';
