import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Stack, Text, PrimaryButton, DefaultButton, MessageBar, MessageBarType } from '@fluentui/react';
import styles from './QuizIntroduction.module.scss';
const QuizIntroduction = ({ onNavigate }) => {
    return (_jsxs(Stack, Object.assign({ tokens: { childrenGap: 30 }, styles: { root: { maxWidth: 800, margin: '0 auto' } } }, { children: [_jsxs(Stack, Object.assign({ horizontalAlign: "center", tokens: { childrenGap: 15 } }, { children: [_jsx(Text, Object.assign({ variant: "xxLarge", styles: { root: { fontWeight: 600, color: '#0078d4' } } }, { children: "\uD83D\uDCDD Quiz d'Introduction" }), void 0), _jsx(Text, Object.assign({ variant: "large", styles: { root: { textAlign: 'center', color: '#605e5c' } } }, { children: "D\u00E9couvrez les comp\u00E9tences fondamentales de CIPREL" }), void 0)] }), void 0), _jsxs(MessageBar, Object.assign({ messageBarType: MessageBarType.info }, { children: [_jsx("strong", { children: "Information :" }, void 0), " Ce quiz vous permettra de vous familiariser avec les comp\u00E9tences cl\u00E9s attendues chez CIPREL. Il n'y a pas de bonnes ou mauvaises r\u00E9ponses."] }), void 0), _jsxs(Stack, Object.assign({ tokens: { childrenGap: 20 } }, { children: [_jsx(Text, Object.assign({ variant: "mediumPlus", styles: { root: { fontWeight: 600 } } }, { children: "\u00C0 quoi vous attendre :" }), void 0), _jsxs("ul", Object.assign({ className: styles.quizList }, { children: [_jsx("li", { children: "\u2705 Questions sur les valeurs et la culture CIPREL" }, void 0), _jsx("li", { children: "\u2705 Comp\u00E9tences techniques de base" }, void 0), _jsx("li", { children: "\u2705 Soft skills et collaboration" }, void 0), _jsx("li", { children: "\u2705 Vision et objectifs de l'entreprise" }, void 0), _jsx("li", { children: "\u2705 Dur\u00E9e estim\u00E9e : 10-15 minutes" }, void 0)] }), void 0)] }), void 0), _jsxs(Stack, Object.assign({ tokens: { childrenGap: 20 } }, { children: [_jsx(Text, Object.assign({ variant: "mediumPlus", styles: { root: { fontWeight: 600 } } }, { children: "Instructions :" }), void 0), _jsxs("ol", Object.assign({ className: styles.instructionsList }, { children: [_jsx("li", { children: "Lisez attentivement chaque question" }, void 0), _jsx("li", { children: "R\u00E9pondez de mani\u00E8re spontan\u00E9e et honn\u00EAte" }, void 0), _jsx("li", { children: "Vous pouvez naviguer entre les questions" }, void 0), _jsx("li", { children: "Votre progression est automatiquement sauvegard\u00E9e" }, void 0)] }), void 0)] }), void 0), _jsxs(MessageBar, Object.assign({ messageBarType: MessageBarType.warning }, { children: [_jsx("strong", { children: "Note :" }, void 0), " Ce quiz est en cours de d\u00E9veloppement. Les questions seront bient\u00F4t disponibles."] }), void 0), _jsxs(Stack, Object.assign({ horizontal: true, horizontalAlign: "center", tokens: { childrenGap: 15 } }, { children: [_jsx(DefaultButton, { text: "\u2190 Retour au tableau de bord", onClick: () => onNavigate('dashboard'), iconProps: { iconName: 'Back' } }, void 0), _jsx(PrimaryButton, { text: "Commencer le Quiz", onClick: () => {
                            // TODO: Start quiz logic
                            alert('Quiz en cours de développement');
                        }, iconProps: { iconName: 'Play' }, disabled: true }, void 0)] }), void 0)] }), void 0));
};
export default QuizIntroduction;
//# sourceMappingURL=QuizIntroduction.js.map