import * as React from 'react';
import { Stack, Text, PrimaryButton, DefaultButton, Card, Icon } from '@fluentui/react';
const cardTokens = { childrenMargin: 12 };
const Dashboard = ({ user, canStartIntro, canStartSurvey, onNavigate }) => {
    return (React.createElement(Stack, { tokens: { childrenGap: 30 } },
        React.createElement(Stack, { horizontalAlign: "center", tokens: { childrenGap: 10 } },
            React.createElement(Text, { variant: "xxLarge", styles: { root: { fontWeight: 600, color: '#0078d4' } } }, "\uD83D\uDE80 D\u00E9marche Comp\u00E9tence CIPREL"),
            React.createElement(Text, { variant: "large", styles: { root: { color: '#605e5c' } } }, "Plateforme de gestion des comp\u00E9tences"),
            user && (React.createElement(Text, { variant: "medium", styles: { root: { color: '#323130' } } },
                "Bienvenue, ",
                user.displayName || user.email || 'Utilisateur'))),
        React.createElement(Stack, { horizontal: true, horizontalAlign: "center", wrap: true, tokens: { childrenGap: 20 } },
            React.createElement(Card, { tokens: cardTokens, styles: { root: { maxWidth: 300, padding: 20 } } },
                React.createElement(Stack, { tokens: { childrenGap: 15 }, horizontalAlign: "center" },
                    React.createElement(Icon, { iconName: "TestBeaker", styles: { root: { fontSize: 48, color: '#0078d4' } } }),
                    React.createElement(Text, { variant: "large", styles: { root: { fontWeight: 600 } } }, "Quiz d'Introduction"),
                    React.createElement(Text, { variant: "medium", styles: { root: { textAlign: 'center' } } }, "D\u00E9couvrez les comp\u00E9tences fondamentales de CIPREL"),
                    React.createElement(PrimaryButton, { text: "Commencer le Quiz", onClick: () => onNavigate('quiz-introduction'), disabled: !canStartIntro, styles: { root: { width: '100%' } } }))),
            React.createElement(Card, { tokens: cardTokens, styles: { root: { maxWidth: 300, padding: 20 } } },
                React.createElement(Stack, { tokens: { childrenGap: 15 }, horizontalAlign: "center" },
                    React.createElement(Icon, { iconName: "Survey", styles: { root: { fontSize: 48, color: '#107c10' } } }),
                    React.createElement(Text, { variant: "large", styles: { root: { fontWeight: 600 } } }, "Sondage Comp\u00E9tences"),
                    React.createElement(Text, { variant: "medium", styles: { root: { textAlign: 'center' } } }, "\u00C9valuez vos comp\u00E9tences actuelles dans diff\u00E9rents domaines"),
                    React.createElement(PrimaryButton, { text: "Commencer le Sondage", onClick: () => onNavigate('quiz-sondage'), disabled: !canStartSurvey, styles: { root: { width: '100%' } } }))),
            React.createElement(Card, { tokens: cardTokens, styles: { root: { maxWidth: 300, padding: 20 } } },
                React.createElement(Stack, { tokens: { childrenGap: 15 }, horizontalAlign: "center" },
                    React.createElement(Icon, { iconName: "ProgressRingDots", styles: { root: { fontSize: 48, color: '#d83b01' } } }),
                    React.createElement(Text, { variant: "large", styles: { root: { fontWeight: 600 } } }, "Suivi des Progr\u00E8s"),
                    React.createElement(Text, { variant: "medium", styles: { root: { textAlign: 'center' } } }, "Consultez votre \u00E9volution et vos r\u00E9sultats"),
                    React.createElement(DefaultButton, { text: "Voir les Progr\u00E8s", onClick: () => onNavigate('progress'), disabled: !user, styles: { root: { width: '100%' } } })))),
        React.createElement(Stack, { tokens: { childrenGap: 20 }, styles: { root: { maxWidth: 800, alignSelf: 'center' } } },
            React.createElement(Text, { variant: "xLarge", styles: { root: { fontWeight: 600, textAlign: 'center' } } }, "\u00C0 propos de la D\u00E9marche Comp\u00E9tence"),
            React.createElement(Stack, { tokens: { childrenGap: 15 } },
                React.createElement(Text, { variant: "medium" },
                    "La ",
                    React.createElement("strong", null, "D\u00E9marche Comp\u00E9tence CIPREL"),
                    " est un programme con\u00E7u pour identifier, d\u00E9velopper et valoriser les comp\u00E9tences de nos collaborateurs."),
                React.createElement(Text, { variant: "medium" },
                    "\uD83C\uDFAF ",
                    React.createElement("strong", null, "Objectifs :")),
                React.createElement("ul", null,
                    React.createElement("li", null, "Identifier les comp\u00E9tences cl\u00E9s de votre poste"),
                    React.createElement("li", null, "\u00C9valuer votre niveau actuel"),
                    React.createElement("li", null, "D\u00E9finir un plan de d\u00E9veloppement personnalis\u00E9"),
                    React.createElement("li", null, "Suivre votre progression dans le temps")),
                React.createElement(Text, { variant: "medium" },
                    "\uD83D\uDCCA ",
                    React.createElement("strong", null, "Processus :"),
                    " Quiz d'introduction \u2192 Sondage d'\u00E9valuation \u2192 Plan de d\u00E9veloppement \u2192 Suivi des progr\u00E8s"))),
        React.createElement(Stack, { horizontalAlign: "center", styles: { root: { marginTop: 40, paddingTop: 20, borderTop: '1px solid #edebe9' } } },
            React.createElement(Text, { variant: "small", styles: { root: { color: '#605e5c' } } }, "\u00A9 2025 CIPREL - Plateforme de Gestion des Comp\u00E9tences"))));
};
export default Dashboard;
//# sourceMappingURL=Dashboard.js.map